### ISSUE TITLE
Float the blocks

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-community-website#16]
Because the content blocks are not the same size, there is too much vertical whitespace between blocks. Can the blocks float? @bwbroersma

**Comment by arianvp** [comment]
I have removed the two-column layout for now, until I find a solution to make the blocks display side-by-side without the whitespace.  

Perhaps we can use https://developer.mozilla.org/en-US/docs/Web/CSS/columns for this?

**Comment by arianvp** [comment]
I'm closing this as we moved away from a 2-column alyout for now
