### ISSUE TITLE
Improve heading structure

### ISSUE THREAD

**Issue by bramd** [minvws/nl-covid19-notification-app-community-website#20]
Now all blocks on the homepage are a heading on level 1 (`h1`). For accessibility it would be better if we:

1. Make the page title a h1 (at the beginning of our main content)
1. Form a logical structure of h2's under that

**Comment by arianvp** [comment]
Sounds good. I will incorporate these changes.

**Comment by arianvp** [comment]
@bramd I made a pull request here https://github.com/minvws/nl-covid19-notification-app-community-website/pull/21 with your suggestions for the markup

I'm trying to find a way to give you the markup of the pull request before it is merged. I don't know how to do that in an automated fashion.
