### ISSUE TITLE
Clicking "Code for NL" link results in NET::ERR_CERT_COMMON_NAME_INVALID error page

### ISSUE THREAD

**Issue by Marc-JB** [minvws/nl-covid19-notification-app-community-website#22]
### Describe the bug, issue or concern
When you click on the link to the Code for NL page - https://codefor.nl/ - an error page from the browser appears with the text "NET::ERR_CERT_COMMON_NAME_INVALID"

### To Reproduce
1. Go to https://minvws.github.io/nl-covid19-notification-app-community-website/
2. Click on the "Code for NL" link (see first screenshot)
3. The browser shows an error page (see second screenshot)

### Expected behavior
The link should redirect to https://www.codefor.nl/ (note the `www`), which works perfectly.

### Screenshots
![image](https://user-images.githubusercontent.com/16156117/85228669-0d491f00-b3e5-11ea-96bc-b528841ba545.png)

![image](https://user-images.githubusercontent.com/16156117/85228885-8eed7c80-b3e6-11ea-9c35-27002048aca4.png)

Browsers tested:

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 83.0.478.54

**Smartphone:**
 - Device: Nokia 7 Plus
 - OS: Android 10
 - Browser: Edge
 - Version: 45.05.24.5036

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by arianvp** [comment]
Thanks. Will fix for now; but i'll also report upstream that they should set up a working redirect =).

**Comment by arianvp** [comment]
https://github.com/minvws/nl-covid19-notification-app-community-website/commit/f3cdc9a6b40e86aebe1f5d23e7e9434aedb57b2c
