### ISSUE TITLE
"In the media" page

### ISSUE THREAD

**Issue by arianvp** [minvws/nl-covid19-notification-app-community-website#35]
A page which lists all the articles where the community is mentioned.

See the figma https://www.figma.com/file/Dmo5nuXcaoxMaNTXDFc9Cw/Status-dashboard-COVID-19-notificatieapp?node-id=453%3A0

Should be very similar to how the `events` page is built. Not that hard to add!

**Comment by EdoPlantinga** [comment]
The community homepage now includes links to 4 articles describing the open proces. Also, in Slack there now is a shared channel for media posts that is well used.
