### ISSUE TITLE
Build nl-design-system ourselves and include results in jekyll build

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-community-website#5]
We now link to [`https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css`](https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css), this currently is the NL Design System 0.1.1, but this version is not included in the URL.
Since there can be breaking changes, see the [upgrade page](https://nl-design-system.gitlab.io/nl-design-system/upgrade/), we should link to a versioned version and have preferably also use [Subresource Integrity (SRI)](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) since this file is external.

*PS: it's not just simply copy the css file over, since it has dependencies on other (relative) resources, and it's also a DUO build, [as can be seem here](https://nl-design-system.gitlab.io/nl-design-system/templates/starter-page/index.html)*

**Comment by arianvp** [comment]
can Jekyll automatically generate SRI tags?

**Comment by bwbroersma** [comment]
We shouldn't automatically generate SRI, that would kind of defeats the whole purpose :wink: .

I think we should make a static build for these VWS sites.

**Comment by arianvp** [comment]
I mean as an output of the build of course :p

**Comment by bwbroersma** [comment]
> I mean as an output of the build of course :p

You can easily generate <span title="Subresource Integrity">SRI</span>, if you trust the file, see the [SRI hash generator](https://www.srihash.org/).
```bash
curl -sSfqA '' --compressed 'https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css' \
 | openssl dgst -sha256 -binary \
 | openssl base64 -A
# TcpPsVA7aFeDShDs6vennop1pZ/5CoLg1UxX+Y6xMrI=
```
so the HTML should be
```html
<link
    href="https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css"
    rel="stylesheet"
    integrity="sha256-TcpPsVA7aFeDShDs6vennop1pZ/5CoLg1UxX+Y6xMrI="
    crossorigin="anonymous">
```
But you *only* want to do this with URLs that will not update the content, so `Cache-Control: immutable` or the promise of it being immutable.

**Comment by bwbroersma** [comment]
BTW There is also something weird about the styling of the list, the difference in `margin-left` is caused by the order of the styles.
On the left the inspector of the first list on [the component page](
https://nl-design-system.gitlab.io/nl-design-system/templates/componenten-page/) and on the right the [current website](https://minvws.github.io/nl-covid19-notification-app-community-website/):
![inspector screenshot](https://user-images.githubusercontent.com/4252918/84570724-98943600-ad8f-11ea-809b-6ebf14a8ccee.png)

**Comment by arianvp** [comment]
that seems to be a bug on their side then in how they assemble this `uno.css`  hmm.

**Comment by arianvp** [comment]
This is a blocker for Launch in my opinion. If somebody could pick this up (e.g. integrating `uno` in the jekyll build system this would be _highly_ appreciated!)

**Comment by arianvp** [comment]
I now include nl-design-system directly into the build
