### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp]

### ISSUE THREAD

**Issue by mjpsbtech** [minvws/nl-covid19-notification-app-community-website#56]
### Typo in public documentation

I have found a Typo in the public documentation. I did not found another place to report them, so I hope it's useful here. Congrats with the app, as a professional working for digitalisation of Public sector I think the way privacy and other possible concerns are treated is good enough, and this is important for our society. 

Privacyverklaring paragraaf 6 (iOS versie): 1e woord: HeHet

**Comment by EdoPlantinga** [comment]
There is now a new privacy statement. Closing this issue.
