### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp]

### ISSUE THREAD

**Issue by mjpsbtech** [minvws/nl-covid19-notification-app-community-website#57]
### Suggestion for Technische uitleg punt 5

The text does not make clear how you receive the notification / melding. I suppose it is local, as you are asked as a user to agree with notifications from the app. The text can be improved to make sure the reader will not suppose that there is a kind of "big brother" who is able to see that you have encountered a person with covid. So it's better to explain that this notification is local and nobody else is able to see it.

**Comment by EdoPlantinga** [comment]
This does not seem to relate to the community website. I think the local working of the app is sufficiently explained in the explainer videos.
