### ISSUE TITLE
App disabled by batery saving mode phone

### ISSUE THREAD

**Issue by IvorNetJam** [minvws/nl-covid19-notification-app-community-website#67]
I'm using a Galaxy 10+ and like earlier models it has a features that disables certains apps that stay active in the background.

I noticed this while going through my installed apps, seeing which I could remove.

I think

`<uses-permission android:name="android.permission.WAKE_LOCK" tools:node="remove" />
`

is missing

**Comment by hvisser** [comment]
Please file this on https://github.com/minvws/nl-covid19-notification-app-android/issues, thanks!
