### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-community-website#7]
*I didn't want to include myself on PR #4 :wink:*

I really like the [Svelte](https://svelte.dev/) contributors section on their front-page, it includes a list Github avatars linked to the Github profile, sorted on contributions. We could re-use [their script](https://github.com/sveltejs/svelte/blob/master/site/scripts/get-contributors.js) to generate a JPG spite + URL array, maybe change it to export YML instead and run it in a GitHub Action to auto-generate these files.

Other thoughts?

**Comment by arianvp** [comment]
@EdoPlantinga wanted to have a section of the website dedicated to  _mensen in het zonnetje zettten_  also curious what his idea about this is

**Comment by bwbroersma** [comment]
It would be great to have a dedicated section with more 'what' did these people do (which will be partly manual input), preferably also an indicator to see if a contributor was volunteering or on the payroll to do this. For now, maybe it's better to have a Github icon in the footer that links to this repo, and a Svelte-like contributor list?

**Comment by EdoPlantinga** [comment]
I would like a public thank you for people like yourselves that volunteered for this project. It can also link to the (paid) VWS team overview that I am preparing in Airtable. I really like the Svelte example, but how would that work for non-Githubbers that contributed in other ways? Maybe some hybrid approach? I would also like to state what they did for the project. 
Let's go for an MVP approach (a simple list of names linking to a public profile with a brief description) and work from there? Would not mind going for a full-blown gamification-style badge overview at some stage.

**Comment by arianvp** [comment]
I am gonna consider this closed; with the list Edo is keeping up to date.

An automated system a la svelte would be nice but I think we'll just do it manually for now
